apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-config
  namespace: ecommerce
data:
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-service:3306/ecommerce_db?createDatabaseIfNotExist=true"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_JPA_SHOW_SQL: "false"
  SERVER_PORT: "8080"
